QueroCafe/Models/Entity/Cafe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QueroCafe.Models.Entity
{
    public class Cafe
    {
        public int ID { get; set; }

        public Agenda Agenda { get; set; }

        public int QtdXicaras { get; set; }

        public CafeStatus Status { get; set; }

        public DateTime DataCriacao { get; set; }
    }
}

QueroCafe/Controllers/CafeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using QueroCafe.Models;
using QueroCafe.Models.Entity;
using QueroCafe.Models.Repository;
using QueroCafe.Models.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QueroCafe.Controllers
{
    public class CafeController : Controller
    {
        private readonly CafeRepository cafeRepository;
        private readonly CafeHistoricoRepository cafeHistoricoRepository;
        private readonly UsuarioRepository usuarioRepository;

        public CafeController(IConfiguration configuration)
        {
            cafeRepository = new CafeRepository(configuration);
            cafeHistoricoRepository = new CafeHistoricoRepository(configuration);
            usuarioRepository = new UsuarioRepository(configuration);
        }

        public IActionResult Index()
        {
            var cafe = cafeRepository.BuscarPorStatus(CafeStatus.Pronto);

            if (cafe == null)
                cafe = cafeRepository.BuscarPorStatus(CafeStatus.Comprado);

            return View(cafe);
        }

        public IActionResult Preparar(int cafeID)
        {
            var cafe = cafeRepository.BuscarPorID(cafeID);

            cafe.Status = CafeStatus.Preparando;

            cafeRepository.Atualizar(cafe);
            cafeHistoricoRepository.Incluir(new CafeHistorico()
            {
                CafeID = cafeID,
                UsuarioID = Sessao.IdUsuario,
                Status = CafeStatus.Preparando
            });

            return View("Index", cafe);
        }

        public IActionResult Pronto(int cafeID)
        {
            var cafe = cafeRepository.BuscarPorID(cafeID);
            var usuarios = usuarioRepository.ListarUsuarios();
            var email = new EmailService();

            cafe.Status = CafeStatus.Pronto;

            cafeRepository.Atualizar(cafe);
            cafeHistoricoRepository.Incluir(new CafeHistorico()
            {
                CafeID = cafeID,
                UsuarioID = Sessao.IdUsuario,
                Status = CafeStatus.Pronto
            });

            foreach (var usuario in usuarios)
            {
                email.EnvioEmail(usuario, $"{Sessao.NomeUsuario} acabou de fazer um cafézinho. Eai bora pegar um pouco? &#128525;");
            }

            return View("Index", cafe);
        }

        public IActionResult Retirar(int cafeID)
        {
            var cafe = cafeRepository.BuscarPorID(cafeID);
            var usuarios = usuarioRepository.ListarUsuarios();
            var email = new EmailService();

            if (cafe.QtdXicaras > 0)
                cafe.QtdXicaras--;
            else
                throw new Exception("Não há mais café para retirar.");

            if (cafe.QtdXicaras == 0)
                cafe.Status = CafeStatus.Esgotado;

            cafeRepository.Atualizar(cafe);
            cafeHistoricoRepository.Incluir(new CafeHistorico()
            {
                CafeID = cafeID,
                UsuarioID = Sessao.IdUsuario,
                Status = CafeStatus.Retirado
            });

            if (cafe.Status == CafeStatus.Esgotado)
            {
                cafeHistoricoRepository.Incluir(new CafeHistorico()
                {
                    CafeID = cafeID,
                    UsuarioID = Sessao.IdUsuario,
                    Status = CafeStatus.Esgotado
                });

                foreach (var usuario in usuarios)
                {
                    email.EnvioEmail(usuario, $"{Sessao.NomeUsuario} pegou a ultima xícara de café &#128546;. Não tem mais café, caso queira pegar um pouco.");
                }
            }

            return View("Index", cafe);
        }
    }
}

QueroCafe/Views/Cafe/Index.cshtml
@model QueroCafe.Models.Entity.Cafe

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Café";
    ViewBag.BackgroudImage = "/img/backgroud-cafe.jpg";
    ViewBag.ViewID = "CAFE";
}

@section head {
    <link rel="stylesheet" href="~/css/cafe-icon.css" type="text/css" />
}

<div class="painel">
    @if (Model == null || Model.Status == QueroCafe.Models.Entity.CafeStatus.Esgotado)
    {
        <h2>Não há mais café disponivel</h2>
    }
    else if (Model.Status == QueroCafe.Models.Entity.CafeStatus.Comprado)
    {
        <h2>Disponivel</h2>
        <a class="btn" href="@Url.Action("Preparar", "Cafe", new { CafeID = Model.ID })">
            Preparar Café
        </a>
    }
    else if (Model.Status == QueroCafe.Models.Entity.CafeStatus.Preparando)
    {
        <h2>Preparando...</h2>

        <div class="cafe-icon">
            <div class="cafe-icon-asa"></div>
            <div class="cafe-icon-nivel"></div>
        </div>

        <script>
            setTimeout(function () {
                window.location.href = '@Url.Action("Pronto", "Cafe", new { CafeID = Model.ID })';
            }, 7000);

            setInterval(function () {
                var cafeIcon = document.getElementsByClassName('cafe-icon-nivel').item(0);
                var altura = parseInt((cafeIcon.style.height || '0%').match(/\d/g).join(''));

                altura = altura + 20 < 100 ? altura + 20 : 10;

                console.log(altura + '%');
                cafeIcon.style.height = altura + '%';
            }, 750);
        </script>
    }
    else if (Model.Status == QueroCafe.Models.Entity.CafeStatus.Pronto)
    {
        <h2>Disponiveis @Model.QtdXicaras xícaras de café para consumo</h2>

        <div class="cafe-icon">
            <div class="cafe-icon-asa"></div>
            <div class="cafe-icon-nivel" style="height: @($"{(Model.QtdXicaras * 100) / 5}%")"></div>
        </div>

        <a class="btn btn-full" href="@Url.Action("Retirar", "Cafe", new { CafeID = Model.ID })">
            Pegar 1 xícara de café
        </a>
    }
</div>