QueroCafe/Models/Entity/Usuario.cs
using System;
namespace QueroCafe.Models.Entity
{
    public class Usuario
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Dd { get; set; }
        public string Celular { get; set; }
        public string Senha { get; set; }
        public DateTime dataModificacao { get; set; }
        public bool Ativo { get; set; }
        public bool Bloqueado { get; set; }

    }
}

QueroCafe/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using QueroCafe.Models.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using QueroCafe.Models;
using System.Text.RegularExpressions;
using QueroCafe.Models.Entity;
using QueroCafe.Filters;
using QueroCafe.Models.Service;

namespace QueroCafe.Controllers
{
    [Autenticacao]
    public class UsuarioController : Controller
    {
        private readonly IConfiguration _configuration;

        public UsuarioController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            var usuarioRepository = new UsuarioRepository(_configuration);
            var usuarios =  usuarioRepository.ListarUsuariosAtivosInativos();
            return View(usuarios);
        }

        public IActionResult Criar()
        {
            var usuario = new Usuario();
            return View(usuario);
        }

        public IActionResult Editar(int id)
        {
            var usuarioRepository = new UsuarioRepository(_configuration);
            var usuario = usuarioRepository.ListarUsuario(id);
            return View("Criar", usuario);
        }

        public IActionResult CriarUsuario(string txtnome, string txtemail, string txtcelular, int id, int codigoSituacao)
        {
            var usuario = new Usuario();
            if (txtnome != null && txtemail != null && txtcelular != null)
            {
                usuario.Nome = txtnome;
                usuario.Email = txtemail;
                usuario.Dd = txtcelular.Substring(0, 2);
                usuario.Celular = txtcelular.Substring(2, 9);
                if (codigoSituacao == 0)
                    usuario.Ativo = false;
                else
                    usuario.Ativo = true;
                var usuarioRepository = new UsuarioRepository(_configuration);
                if(id != 0 )
                {
                    usuario.Id = id;
                    if (usuarioRepository.AlterarUsuario(usuario))
                    {
                        ViewBag.Sucesso = true;
                    }
                    else
                        ViewBag.Sucesso = false;
                }
                else
                {
                    if (usuarioRepository.CriarUsuario(usuario))
                    {
                        var enviarEmail = new EmailService();
                        enviarEmail.EnvioEmail(usuario, "Novo usuário, SEJA BEM VINDO!");
                        ViewBag.Sucesso = true;
                        return View("Criar", new Usuario());
                    }
                    else
                        ViewBag.Sucesso = false;
                }
                
            }
            else
                ViewBag.Sucesso = false;

            return View("Criar", usuario);
        }
    }
}

QueroCafe/Views/Usuario/Criar.cshtml
@model QueroCafe.Models.Entity.Usuario
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Usuário";
    ViewBag.ViewID = "USUARIOS";
    ViewBag.BackgroudImage = "/img/backgroud-usuario.jpg";
}

@section head {
    <script src="~/js/validacao.js" type="text/javascript"></script>
}

@if (ViewBag.Sucesso == true && Model.Id != 0)
{
    <div class="alerta sucesso">Usuário alterado com sucesso.</div>
}
else if (ViewBag.Sucesso == true && Model.Id == 0)
{
    <div class="alerta sucesso">Usuário criado com sucesso.</div>
}
else if (ViewBag.Sucesso == false && Model.Id != 0)
{
    <div class="alerta erro">Erro ao alterar usuario.</div>
}
else if (ViewBag.Sucesso == false && Model.Id == 0)
{
    <div class="alerta erro">Erro ao criar usuario.</div>
}

<form method="post" action="@Url.Action("CriarUsuario","Usuario", new { id = Model.Id})" onsubmit="return validacao(this)" class="painel">
    @if (Model.Id != 0)
    {
        <h2>Alterar Usuário</h2>
    }
    else
    {
        <h2>Cadastro Novo Usuário</h2>
    }
    <div class="content">
        <label for="nome" class="label">Nome: </label>
        <input type="text" name="txtnome" class="form-control" size="40" value="@Model.Nome" />
    </div>
    <div class="content">
        <label for="email" class="label">E-mail: </label>
        @if (Model.Id != 0)
        {
            <input type="text" name="txtemail" class="form-control" size="40" value="@Model.Email" readonly />
        }
        else
        {
            <input type="text" name="txtemail" class="form-control" size="40" value="@Model.Email" />
        }
    </div>
    <div class="content">
        <label for="celular" class="label">Celular: </label>
        <input type="text" onkeypress='return AceitaApenasNumero(event)' name="txtcelular" class="form-control" size="40" value="@Model.Dd@Model.Celular" />
    </div>
    <div class="content">
        <label for="cbxSituacao" class="label">Situação: </label>
        <select id="codigoSituacao" name="codigoSituacao" class="form-control">
            @if (Model.Id == 0)
            {
                <option value="2" selected></option>
                <option value="1">Ativar</option>
                <option value="0">Inativar</option>
            }
            else if (Model.Id != 0 && Model.Ativo == true)
            {
                <option value="2"></option>
                <option value="1" selected>Ativar</option>
                <option value="0">Inativar</option>
            }
            else if (Model.Id != 0 && Model.Ativo == false)
            {
                <option value="2"></option>
                <option value="1">Ativar</option>
                <option value="0" selected>Inativar</option>
            }
        </select>
    </div>
    <div class="content">
        @if (Model.Id != 0)
        {
            <button class="btn btn-full" size="20">Alterar</button>
        }
        else
        {
            <button class="btn btn-full" size="20">Criar</button>
        }
    </div>
</form>

QueroCafe/Views/Usuario/Index.cshtml
@model List<QueroCafe.Models.Entity.Usuario>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Usuário";
    ViewBag.ViewID = "USUARIOS";
    ViewBag.BackgroudImage = "/img/backgroud-usuario.jpg";
}

<div class="painel" style="width: 50%">
    <h2 style="display: inline-block">Lista de Usuários</h2>
    <a href="@Url.Action("Criar", "Usuario")" class="btn btn-direita">Adicionar</a>
    @if (Model.Count > 0)
    {
    <table>
        <thead>
            <tr>
                <th width="60%">Nome Usuario</th>
                <th width="20%" class="texto-central">Email</th>
                <th width="20%" class="texto-central">#</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var usuario in Model)
        {
            <tr>
                <td width="60%">
                    <div class="identidade">
                        <img src="~/img/usuario.png" />
                        <span>@usuario.Nome</span>
                    </div>
                </td>
                <td width="20%" class="texto-central">
                    @usuario.Email
                </td>
                <td width="20%" class="texto-central">
                    <a href="@Url.Action("Editar", "Usuario", new{ id = usuario.Id})" class="btn btn-direita">Alterar</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
    }
    else
    {
    <h3 class="texto-central">Sem usuários cadastrados</h3>
    }

</div>